apiVersion: v1
kind: Secret
metadata:
  name: crud-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
stringData:
  db_url: "mysql://{{ .Values.db.user }}:{{ .Values.db.pass }}@{{ .Release.Name }}-mariadb/{{ .Values.db.dbname }}"
