apiVersion: v2
name: helm-otus-18
description: An app with prometheus/grafana monitoring
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
- name: mariadb
  version: "18.2.6"
  repository: "https://charts.bitnami.com/bitnami"
- name: prometheus
  version: 25.24.1
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus.enabled
- name: grafana
  version: 8.3.6
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled

