{
 "title": "FastAPI Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Quantile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_highr_seconds_bucket[1m])) by (le))",
     "legendFormat": "Quantile 0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_highr_seconds_bucket[1m])) by (le))",
     "legendFormat": "Quantile 0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_highr_seconds_bucket[1m])) by (le))",
     "legendFormat": "Quantile 0.99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(http_request_duration_highr_seconds_bucket[1m])) by (le))",
     "legendFormat": "Quantile max"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"$job\"}[1m])",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Errors per second 5xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"5xx\"}[2m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Request per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  }
 ]
}